services:
  dsemu:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:555.0.0-emulators
    ports:
      - "8081:8081"
    command: gcloud --project=datastore-wrapper emulators firestore start --host-port=0.0.0.0:8081 --database-mode=datastore-mode

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  memcached:
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
